name: Build WORLD Browser
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build Desktop App
        run: tauri build --bundles msi,exe
